---
apiVersion: v1
data:
  BROADCAST_RCON_TO_OPS: ""
  RCON_CMDS_FIRST_CONNECT: ""
  RCON_CMDS_LAST_DISCONNECT: ""
  RCON_CMDS_ON_CONNECT: ""
  RCON_CMDS_ON_DISCONNECT: ""
  RCON_CMDS_STARTUP: ""
kind: Secret
metadata:
  name: rcon-cmd-ops-secret
  namespace: ontampa-devs-gaming
type: Opaque
---
apiVersion: v1
data:
  forwarding.secret: ""
kind: Secret
metadata:
  name: forwarding-secret
  namespace: ontampa-devs-gaming
type: Opaque
---
apiVersion: v1
data:
  ENABLE_RCON: "" 
  RCON_PASSWORD: ""
  RCON_PORT: ""
kind: Secret
metadata:
  name: rcon-initial-secret
  namespace: ontampa-devs-gaming
type: Opaque
