---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forwarding-secret
  namespace: ontampa-devs-gaming
spec:
  encryptedData:
    forwarding.secret: AgBQVBP5z4vf4K7RxFjmQtb8RPuxLuGluvvNGhezvBiweOmm+0Zsa1BBo8qA29v0iXx5XxcqOf6YSMGomKt5jx+aB4CeZWtVsUQae56UsbzzU+RBdLOYd6X05qqoO5EA0bfHSS8WOIOSYS5SyobppU8ohIJDU+FTbVzoeCfH49EuNfL1dXecCfP6CytUWp2jzDZAP+JvpbtMSWRdsDue4WTRRMhNfYB9088TgLl0ZY/2nD58sBnDF8dPlCM6Gk2eVbEP1iAKxBqvgq8o04z9Xvt0kEu+NCGJW7DnMb/syRLSVZ1zGB43tsuX7nxuVBFRlGIWnXJkkI9212w1NC0bKGad1nxuWuiEH71whh6S5ypyKESBFSdJAcsCX5rANm5cMWwhLDkJzRY3RIfEJref+EagFr3xyIIyzWzr0QHQAUN7sKtQ8gpLp8bEG7i5+NbSM1LLq/sHEn5fZeQTQDT4ZyoQzPunT+w98KDCu/5PwuxznWgPdKAgdPp+8hjmzPfJhCLhVGafOp5g/BIGm0btMKMg2kY6yPqWiGErxaecVaEYeEabpPNMEec9m7kcurZfphLI6rXmUyyv/GRuZg6JBPoc1VabhI5hNhBnSYqAbHEZPaTiik9bSR8CfARxgpxwDAIgeXsd1SLbd8vRPqluSsRZVPg3Z3S49KR6OF8mXVchEdOzjCMDvMIOnz5uyqv0ZgjB9jYHq52/OIO2sMk=
  template:
    metadata:
      creationTimestamp: null
      name: forwarding-secret
      namespace: ontampa-devs-gaming
    type: Opaque
