{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bridge-postgres-synapse-secret",
    "namespace": "ontampa-devs-chats"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bridge-postgres-synapse-secret",
        "namespace": "ontampa-devs-chats"
      }
    },
    "encryptedData": {
      "POSTGRESQL_ADMIN_PASSWORD": "AgAwnYNiqatSNLD/+uBWTKwcjm8DsyRDCRhxS7Io1JqFVoDNiJMFHqmbPmkWx7DStG7Qx4i4BHwi2LgBJQhbDgYAzF6XvmF0QhNBJD/U2Xc6PJNociBB7k2gI8gwRwuxPnDUmsrrnwvxDs8tiekqzTSLuultwxpluBEcuHkglgYlOH0z/84DseWxlL9Lg2ItplGSmiGK19Z+8UfkOry628w9WkY+A5G3eTPP+eSaM3vC2LwNda7QhAc1NQmLOIjV10o2dkUkAaXGRQD7LRhdoGbWwGSPuOL/wWlpm19Bc+QKC0wAvX6GFGvMZj4WHXRIOmmWQbXp0LtG8WCPvuEY9ShnIkSuSkOnwtHeJSOPOT+O2Ze1Lu5UjvXA2PmyC9NXkvmskDDb6tRrhX+LQuWwYE0s4KPud9aG1xkdzhCVxHAVDrwqbPyZ/kZ+oRdWkanWrXu4OlWUNOow524L2ydY4r+KNZgA8ZmdDiG9RYvqH9zOdiJSf+jU73eKxt5NDJo+U89o1MoGFqQUb6jnTyMAfeevdMdmFZZ22BV37XFaSQJJmz93nEqPuuNieOIG07Sm18xutF9fjiU3gJN7AHgyIH42BIE3XPo6KqVv5TuOe7NzQl8KjfHiqqGtYesFUmt1r8Rl/2OTnQt3G/mr8/VHX504fR8Zq6VPu7nMg7secLFwRgd5iWCnuXyOmZ4mChljCaz0MBu/yx4H7fxob21fA3jgwK48M3Ox4KkfiToyjxX12A==",
      "POSTGRESQL_DATABASE": "AgBkvVUdg60szLJhchLEfzPOGmhRyv0XN1IPOvFYoxC1dkJgHdJNyuGpUG55JVMZTzJqdRT5SfNb34JryvnalJP+5bBdMrQwdwbNklrmycbgC12dwTLk99SwAoSKIIjJz1DC+Ga3JxrzTJDC2DUBrRNJ2zzK3I2s8up7X/jyKxDfbsAnelJdTj0TnaO8VKYALaK8Za0yq7d8+QiiLclpQ2nmn8qv3+D3cZ4S0t8kHCtMXcNSCzOl7C/XgMgT77VZ3lCeRm/877B4U/aG3Yc4R8ZtfYSgC8L258sNbgbtln+0ZXRxRlGShT/7QNnzxkb19I5oLolOqWd9BGv2/l9UZcmO3n9YBFn0YeAOqSGwcI0DF21HgAqgiU8HDM5ot9LuXuSMmqHX4DS0eXV13wdIX35u1Z4QqekszpjBTveeGYisl9wylHh6csW00hQ8FaoxRMXp4BGNbKtIRDs+mvDAYXnBZPATpGHjrsvFpSvz+BhO8Ze9UXEjLzGPKEop8egdP4Sw4929My9Lrm/AhANWAo0ugLwaTYYHWhIZeliFmctZmiu53b5HmFV/nIzE46r1QlWwlSSadawUh7sdqZi/1m6QqMCC3grSJTGIjWRqEJfuJ+gLQ42T5+egqmBHoHCT9wl57ZJHBaOC12K/1uHpyQVloA5mQSmJwbVsXsImzCJESQaXpKykKO/S014PWNQ4RfjDEwRXelEf",
      "POSTGRESQL_PASSWORD": "AgADnoktlprDuMKo9Xn+STh9L418s+mcdarmtu0t00DRS0SK/ij8RalKHSIdIghOjQyLWg7GJsdK/wJJCu3x3BjpRw9YIhi9EfH0NCivlgiNQv3BfeXWfsBjPVEvXelfZE+CphpUi6DbDl4Zg/Eg63O523yoSSoEm3SctTIybiFA712up0fsaY7JJ/myetzkDmInS6j5SiuJ1TR81kixs73pNuBZIkrsdGryhB7EhlnPwhWb6bkA0AYpkzV5mcGNgQOD/HcjYQnLP0AHRNFtAy072cGgn4VXf8EethUCt83M1/vL10ifXqE36u5J8I3qVnpuve8Wl0xbiEGoa8Kb7GPYHYYc9MDQ48KeLekHlMEd8J72JpvQFO/VmHQhcM0qUFPWMzJYNl4hEblnxsFMpiv2ULh1D9mH33PmAwmHPmt6sRyBSsgcU+X0Po2g8RKcl6qtDKlNxkIw0TqakZ7XnC9F3rTI3wU8cbNH/eqig8pvvxWVQKxpVPHalSlB99qLGEithS4s5tDHO1g8UzsQNP3fAhReopb4qlR+ScP1e40uqgG9FzGKU/RmE6JlgyIZTLnHFRDSwmksINhheqxK/ipK4OoAt3xaa7vJpLlpVvmm4yrkjKYo3SHvCumxerDuMi3e8lKkQeaa6wMHdyyy+JKVkEjKeEU/GxAUN/C/VLRVKsZGAl5T+vdRLBUhhYlR4a6Y8ZPUZbavmNZpYIBrQ6veMLNvY8v1G9tT2AOF/i3aog==",
      "POSTGRESQL_USER": "AgAyxrX0W5y5CcFXdoA9VlApuwvIy9/+Q6LMp0N5zRyo8vKd0xaWQi54n59mHerueBHIyBc6Brcd0ywv8r2NLTKf0vHpCdKcEjBYjZAanssupAQTATTi4YnfHGYFioVpPdUeiDYhEvrzoyvi7h12diy6SWRXenqWpNfQTDfjYW/DN4uyi9TUFkJnVKerAuwgWmFTzgcUg2flwqM8pRdNgS9d7PvK93jnjNnp0A0OjBzIKO6cT2hD986ppty6S+LvYToLX91H5+8nqA2GUwbBr/hfpMx/2XQoIANa1KFd+ntS8Yz5OW5b5DENJt5/NXwz6R0Eam/PFl8x4l/0RvdObSGaTwQdNciYBi7Tbtaov0BJXUuhfPaD5o6/uZw/PP9RhcgUP9sBsLKSIuXClMwOz6zbvK7b9zqYem7nuv0AfWO5Yte09NfMjNsOULJxTxkQageQ7s1cXRl10+K91llXRnHoiXKwRX/Ls07uWhIOSFNS4+rEZ0Ax/6C6axrHGRI00raM81XXWhzt3BZru53033Xmpqjc8q1ntQQQjGEVWTnk31ZpvMCB6yZUVxBZmZS3hEKmKeyRsKNY7lqMaWegD10f09Eogy6E9FEU+KG89Pz7Is8Elt1+BR5+x4tfvCGEJdxF88GINkk7eva3rw/N97HD+BqTnloi1hrljPdwjlvy+S+pe5uw+gaj1dsBy7GRHFUbUlmaKGWG"
    }
  }
}
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bridge-postgres-mas-secret",
    "namespace": "ontampa-devs-chats"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bridge-postgres-mas-secret",
        "namespace": "ontampa-devs-chats"
      }
    },
    "encryptedData": {
      "POSTGRESQL_ADMIN_PASSWORD": "AgCdsITghe32u83gyHDYwKKzYRk2CChe8B4F0RX6tbzK4fhd+T0EFpjqVfNNtD1UjBqFtZgs/DS+D9hsvhc0X0G6p9WpgH3xmIg3DtYSLLjsv5125CWkY+VBODQkTiZnO4DScsW6sD5HKOg0K7g9/lIFI1MQTQbf7ke+qIDkH3dkV+UwhvSuldixxOjVpPsmUyz7l92CmrPAFvLgglkSsUdkCgltF3q9BkJTjks2tUXF1uOM0vOxswkhV5Ufjtvix/r+XQdfKlccyx9JUbLA3plpQE7tpAU63wKDuu9s4wLlUfBrmNXv2rBy/QoEgDpRj1nuCSIu2ZxYk6/psMxWIL6pAqr+qUTQ/9OSouB+802ajoyPUnAMKuxMKbkAUq96TJTM4VLaBrGT++UpRpPuW9WRFUaG8sjdUfwdvoHsdQFGRMr9eRDGtGok+zAl63HB0npR6kmI00g3LNVGqRtizFdS8lnYbkJiNPvbrK3wUYZQIf5+1yOYfI6tGLJYDUpeOrLYFRdc9zrbHzo3PT+u/vkoj680oumktIn8vu5XtE1LUWuw755Ke9NKAtpZGNJo0RIdhm1nc8xbEkMxvdu5yWGvA8PsuQ6AHEL1Io6tTwPZ5OrkeAxStc8lEf11nAh0gPWTmcTCddusK0QHmrKeeIyNCfwyN9Bpu7a76rDuZJyp86FEqqQkSV9R0AsKYJszMQXVNX6hl3I8GPn59MrurWhG0lsgSNWls731LEtTtRoVtg==",
      "POSTGRESQL_DATABASE": "AgCLB0+VfpQQHuHtfTEzuGM3ojje5LWf1FJ3SGjHpgpU8ThIOtoS+yOvPNiiPKzFmWQkCxicc8yYXcKfF8mWAYNKZVKHP3XGAL1wspAAJGTn1DqN5cOANP3v/aEw2xRpJGVgVnCJJM1OYV5j4XHNWBvaHlA/f9re7XKx4MJTmUojrj0A6u39WgURijTLg1ciQJzAp9TU41m1xRoiyUoSeKnH0f9+jV6cCAK46cMzcD1tOyUjmy/Eppw+YFhZZN76qAcK7Gd72UoIT43H643GZnBKLqJeD8b00Zaus3d4TlTmraXItT9bv9y2Ztseizb9FYU0vDkzT1dwOqXLBgn1TQa1YfFUQYlyE6+ST9DTXJS/JuDZfqz8c829MvE+MHaALYCVEpo38DL6HJt9U6lBZ3we8LmfWIR3XL/WCYhmgjY2pGyiVBaz3mhtlZ+d8BnGZlsRAJjpFuYZj+5rNEE40+6Ktk+O/T2RRlQwD80znf4TI6wryQzKyFE0u4OcLWGB5stjGTYWDBnVGoHadwn8w7UkkxJfa7zTqjkkZaBX0YVgbqKeFwY247+Ki6hfG4gKzGNtVOpwUPqc2+BZN8GCOzZ4T9JNIA2oYqQB0idythbORDIYLDc2zH0SHe1vOwtAy3CzbCaJL+f7NGLLXdmRoDq2Z9wt2xTJkFxLmvzFX5n6o4U6lMAS/vf/6vJ/3knrChAAaYg=",
      "POSTGRESQL_PASSWORD": "AgAJ0L7/WoBMDG9DO3myhX+TFUsS83Slpy8MRrgwR3gCmzinZPc/bz7XYVnHRQIiifUB2kgJjnVdyDvhZwNUZOZS9YkJ8yvlaSzKK/hhNd2Ab1bHqDUFXqT1OSJt/dXBUQg3pjeLpe5bsmddRBxVkLux/HawwQJRdPshC+e2MvJwhh422M03OAIKKZs6a3biOM0m40SLsr9VwLLVNSkjF9TNNhzTJuqemkZZA/DoN53HdWbm3+iCMobl6s/a5NCPzTBa8YdUJ0KRrwZZvH81e/sbZuTbSzouzx8S+FnL17/Ol4R2v3hhTRPiggEKvrfUiLQprpsQ3RWGmbGQjz86bKG6Bw0tVs5hRnLT6Pcyl81aPD5rMOa8LsCxhxKH3nU3TKIV6rQxR+Yiua2N3O51i+4TytjNxtbq7nRFTbDGYz1r0NdYl1AUuImCDeBdj1X1JiZf/sO2LRr+jgSqdWvsHWayMKxtYxrEpxluuVPPP0E2ZD1Cbgdm6rRn9Z9o68+iUF0x2DVqSJ4LVbnDjCVtogCnuf/sLSb9RUjtcHR03q15pji405oZ8aV1R13Nab8jXbCPve4wzg0rfXworhwePhXAH7a9hN8mRo3W3f/qEQ0pgn3+sP36q/xcKx+YynPQ015k+JDvmF6LqQ/i5ocE/86Btp3dlZTxTz3M8RUfe2NnqFdzb/PiBJAmUqitSXna4TaFJagoSNgqTVNcMgceJgvaT5W0OV3ox9amksyR9hH0bQ==",
      "POSTGRESQL_USER": "AgBamtg02FayGF1wuhntIxbQsxmwrbv9094ukQpiVfkZrVmOh7KgGWd/ywGZec6yIooasUaM/sZRR4ZPXeCBNrX0imfI170NlRrX/+Gcml1A8L29gG4n43BfEKrAITq45zmVc8MqvrgOwu7e7DmrLpxYCoSR/zr+W4qKIRPiMMIIkQDO0sdEkX/MGdZpiDDv/e3+CDzB2qiQyGmAAaN0kxD++BsYbxJGF+3WxDUcwE7qVaI7K4r85VH5atylP0JycJji23n7j/YqMPLMeJAyRNh6K4Lpw7P5DcPPfuceJFzzD5DaPm/fuJ4YfA5O1QdzNHaI9tLs6UaTvwkW6ivadmLvvdojWcEkjizeG1DOWZgPSGh3YKWu7fIZi1Srw5+jNj95gilJErBlwLUdmQYOZ0+Ufw0cWVHcp5/pjAlLdKOf0nOmBp4NysJF2eKqI1TieJmlSOw5GwboLcryChE/kEzYjUJU/O8epz8ocSRVMwuD0hIvBslnxmTLAPEB7BwyAduIXWsN5WOZ67PzO2OhQGoMilPRrdFj6Bit6+tV+unwDSKgaUzNImcju65IlxztrD3tmQWdGPKcJZqSX5u4YBPUiYeOb4iM8r2z4EZB2+dXLv5yJsQXXbuFJA/ce++tLTarzxk70HzfvYfT3OmXTucRWNWk/ZoM8qZj4JL1CW29+AWNlOcfKwi8hijnkcSwXJWoJoM="
    }
  }
}
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bridge-postgres-secrets",
    "namespace": "ontampa-devs-chats"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bridge-postgres-secrets",
        "namespace": "ontampa-devs-chats"
      }
    },
    "encryptedData": {
      "mas-auth": "AgC03NiLUabHidkW4wb2LgtKw+8CU5TmhvlB9HemhavQpOHidzLscAk7ekP8m22JzDqpQe5Bc8sLsNkES+wTVU7tJbJnKAQ6CLJrlFzk5uQUAeHj5hqwQIRLwVEMmBTS8MTVEJTFYIE7BkkyIijYjeSm/ImaliJD1j0O8D/D9182sHRMP8zaOPvo33TZ95k5KcIsRVl7l58D/DVm6xA35W2QUdqtrHyTI7WJf4zzNvc9kOLnDaoWfMzx82czKFpX/4/lTQk9FC5swWOiq6eJmOLnK8HC93Ev/7lkXXbs26kty3keeIbn6NbdRqJWjUCu6fcJXwrmbltRk8GudUS52vpLw2hPiCEn1D61vUriolDoLKJr9u5Smds3NpRjakbvTVMYZRLjFyeHmZEgv0Wg480kwKYG265YhBOT7bsyvVMIPoTlZuDhohNbfX9LyPevaV5Jkj+xx7c0U5pReDMfqtPlqfvZrSlS5jAfnjFnboLoHrzgAvB+hgfEz2OOMlbc6O+ABJCat9Kd+da/H8qfwi3OhLbpN0SwUHJ5pFJXEGfT2//oCfUBt+KbYg1cVj+PH5Ug+pNtk4RvNxlAdIPfJlkqnoCi/9Y6TiPR7YZz9yuyWLsmXu2KLfpmagIe2JWZpUgyJurCB7WpiaWfSDadkcnpKkD0IH0kdo/mhD1aw0zfvTGkjh0XPvZYP6JOuk94WOuCtJNFw18v3Jvz1DfvGnMOfrxU0buf/Q7nK6G15zMGsg==",
      "synapse-auth": "AgBiXp1QsBkBYhzi+dBhOQCGfT02+Bpi/bucgrXE8Wty/brZZ2OTU7c9HFgAhZDu+HJ93amMYDkIXMfKx/hfM3aoYpzednZ443V+dWSXxh/oo6GXhnftzTZuL6xazgKyUUQVdMOnsUIZ85N41rSAYlcfC6D4G6LSjF9gwpssPm05pBIhmmL1tZ6602lfH01bTvAEJhEO4+lJTItoNvnI7qC5ZLN9Nk3vWwf25Lj6S4fpXX138kYYqKyOOE/Oybo56qzd7BxJ7hZq/SyZRVOVVhxriomm3FyFAkVmdLPzNFNShG/i0KP0ZIpJNx+lGZPS80bWPBQQSmHKFB34Km6Z+Y4Us073z2irIRJjJZ58JKj+okLhIxncvMG58RUH84if8QoWBIt95Kah3DI7phmqC2Rx6qisWUpBl/AKkJhBF4dH8XpS0PSGvU880TXc2wAzdzdkC5Kc1xxEKUwiIBJfarL5xFzcktCPenXLUaqyMjrwicn0zyZ8y0mNWjbcYCww6OY7gm3YsJAX/OJrsjkfOv46Uk4M+1NZ+6F58q7X8NyQZ1HJsSaf5NIm4eav5apfu0g7RZa1tx+I6JpqFs79cgo87x1OTHKvwpuA82bB00VCOWq0Mhe/VKFombxx/DmxiLuiBmvGzruWXPWQGkt3gbozkq1dRS6CFpW9APM1yPZHWhyp9cq5JpMom8R9wC+ekQ0lNG171KzdT88oVqIldUGnqpqOL7fNsIdaklRvLKZEcg=="
    }
  }
}
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bridge-oidc-tampa-dev",
    "namespace": "ontampa-devs-chats"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bridge-oidc-tampa-dev",
        "namespace": "ontampa-devs-chats"
      }
    },
    "encryptedData": {
      "client_secret": "AgBqedKZr2P2SU0VW8R4xPWcv6lWUeOf1ckVjYpPxrOtCcLGrGUTK+RbXi4YMhIHbRPEF4IJXCZRxWlhFBMnjm1v6b2tGC/IY7ke24h6GV+W2yXu+EiJ1hgxNDLdNk6bWxGD6zfPi4L4ABLLYBsxVUL0ddLNQ79zlOxZzK9pXvgrZCTgEclYlepl1DBClnt2IFmaST15RdPjG5qeIby0YPDyMEZ+TmRNrVmp21YXNnxdcd4mWkYOtHziAsWEhNI00lpz7Sv59J7+ZFywV5zPJFDttsUg39Bc0EEdpRyx9BQWkPOYgy0BmHkycOnSXYrbnPLOnK0jcOqVEOPneKI6oE1vGtLwF6gEUfSwM0pMGvnukao3Jfi1BSIBCTLr2LwPkBDBV/W6nHNzlz9pd/2TCGmk1zVXnVgC7omiEiJDmnfLxUQv6vcVUrSDB7FlyY5WN8IM6rtUUYMS5masWaob+F+oGtJzAjprkjfk3So+u2my1M3uscEoen9E0timnbUwOZRAWYRHMOu+cN5207EDwrF0KExrxkgyK9CSScgD4W26T3w8p+MdZXcM9y/vhZxmzh53skhsYRx3h6d3nhO+JmNKGO0uOhkuOBb+mxzQ6Udm8/CtW6PI7BIRsOPDrZ80H92DwI466PylyKFfyc8uik2jowalPsmbwairsxGJgEQGGw4vgP/fL/76wVZRGl/VsidvAKqzVmAPqzv7YraWAcnNhNrPTyDRRcYltdFSph3Bo7rR615bcNQJto4lM+33I9W/y3NsfMHOJQkMtUzk5lBoinjLdw=="
    }
  }
}
