---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: issuer-letsencrypt-production
  namespace: ontampa-devs-chats
spec:
  acme:
    email: cloud@tampa.dev
    privateKeySecretRef:
      key: tls.key
      name: issuer-acme
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: token
            name: token-api
          email: justin@tampa.dev
        cnameStrategy: Follow
      selector:
        dnsZones:
        - ontampa.dev
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-slack
  namespace: ontampa-devs-chats
spec:
  dnsNames:
    - ontampa.dev
    - chat.ontampa.dev
    - matrix.ontampa.dev
    - account.ontampa.dev
    - admin.ontampa.dev
    - mrtc.ontampa.dev
  duration: 2160h
  isCA: false
  issuerRef:
    kind: Issuer
    name: issuer-letsencrypt-production
  privateKey:
    algorithm: ECDSA
  renewBefore: 360h
  secretName: tls-certificate-chat-ontampa-dev
  secretTemplate:
    annotations:
      sealedsecrets.bitnami.com/managed: "true"
