---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bridge-postgres-synapse-pvc
  namespace: ontampa-devs-chats
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: block

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bridge-postgres-mas-pvc
  namespace: ontampa-devs-chats
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: block
