---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ontampa-devs-glxgears
  namespace: argo-plattform
spec:
  project: cloud-development-gitops-apps
  source:
    repoURL: git@github.com:TampaDevs/cloud-development-gitops-apps.git 
    path: charts/ontampa-devs/glxgears
    targetRevision: main
    helm:
      valueFiles:
        - values-gaspar.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ontampa-devs-glxgears
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
